"""Build portable, self-contained HTML reports from recorded numerical results."""
import base64,csv,html,json,platform
from pathlib import Path

STYLE='''body{font:17px/1.6 system-ui,Segoe UI,sans-serif;color:#203239;background:#f5f7f7;margin:0}main{max-width:1080px;margin:auto;padding:42px 32px;background:white}h1{font-size:38px;line-height:1.15;max-width:850px}h2{font-size:25px;margin-top:38px;color:#14676b}h3{font-size:20px}p{max-width:930px}.eyebrow{color:#14676b;text-transform:uppercase;letter-spacing:.12em;font-size:13px;font-weight:700}.lead{font-size:22px}.note{padding:18px 22px;background:#edf5f4;border-left:4px solid #187c7d}.status{font-weight:700;color:#895120}table{border-collapse:collapse;width:100%;font-size:15px;margin:22px 0}th,td{border-bottom:1px solid #d7e0e1;text-align:left;vertical-align:top;padding:10px}th{background:#edf5f4}figure{margin:30px 0}img{width:100%;height:auto}figcaption{font-size:14px;color:#56686c}a{color:#126b80}code{font-size:14px;background:#edf2f2;padding:2px 5px}pre{overflow:auto;background:#edf2f2;padding:18px;font-size:14px}li{margin:7px 0}details{border:1px solid #d7e0e1;padding:16px;margin:22px 0}summary{cursor:pointer;font-weight:bold}footer{font-size:14px;border-top:1px solid #ccc;margin-top:40px;padding-top:16px}@media print{body{background:white}main{padding:0}h2,figure{break-inside:avoid}a{color:inherit}}'''


def page(title,body):
    return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(title)+'</title><style>'+STYLE+'</style><main>'+body+'</main></html>'


def image(name,caption):
    data=base64.b64encode(Path('analysis',name+'.png').read_bytes()).decode()
    return f'<figure><img alt="{html.escape(caption)}" src="data:image/png;base64,{data}"><figcaption>{caption}</figcaption></figure>'


def csvrows(name):return list(csv.DictReader(Path('analysis',name+'.csv').open(encoding='utf-8')))


def main():
    s=json.loads(Path('analysis/summary.json').read_text());e=json.loads(Path('data/execution.json').read_text())
    fx=csvrows('factorial_contrasts');components=csvrows('stress_components');recovery=csvrows('recovery_summary')
    def fmt(r,scale=100):
        precision=3 if scale==1 else 2
        return f"{float(r['mean'])*scale:+.{precision}f} [{float(r['lo'])*scale:+.{precision}f}, {float(r['hi'])*scale:+.{precision}f}]"
    def effect(factor,metric):return next(r for r in fx if r['split']=='replication' and r['phase']=='1' and r['factor']==factor and r['metric']==metric)
    def rec(memory,metric):return next(r for r in recovery if r['memory']==str(memory) and r['metric']==metric)
    body=f'''<div class="eyebrow">Nous-Volition · Streams and Rocks · SIMS study · 9 October 2026 UTC</div>
<h1>SIMS: names, memory, and group boundaries</h1>
<p>Do boundaries come from names, remembered relationships, or the arrangement?</p>
<p><strong>SIMS</strong> are the simulated participants in this six-group experiment.</p>
<p class="lead">Names alone did nothing to these SIMS. Explicit identity preferences and remembered interactions changed their choices. Stress reduced cooperation, but did not automatically strengthen group boundaries.</p>
<p class="note"><strong>Study design:</strong> SIMS interact under specified rules for partner choice, cooperation, memory, and adaptation. Ice, Water, Fog, Mist, Gas (water vapor), and Smoke are the six symbolic group labels.</p>
<p><strong>Actually executed:</strong> {s['completed_ensemble_runs']:,} main and control trajectories; 72 later diagnostic trajectories; 144 copying-influence assays; 288 synthetic attribution assays; and 35,928 group shuffles. Each trajectory contains 120 rounds. The core has 60 SIMS; sensitivity runs use 30 and 120. Three network arrangements and equal/unequal groups were tested. Twelve discovery seeds and twelve independent replication seeds were used. <strong>All recorded results come from SIMS simulations.</strong></p>
<p><a href="methods.html">Full model and measurements</a> · <a href="human_protocol.html">Optional group-decision game</a> · <a href="analysis/run_phase_metrics.csv">All numerical outcomes</a> · <a href="verification.json">Verification record</a></p>
<h2>What changed in the simulation</h2>
<table><tr><th>Controlled comparison</th><th>Replication result</th><th>Meaning</th></tr>
<tr><td>Neutral names → evocative names → permuted names; no semantic perception</td><td>144/144 comparisons exactly equal; maximum metric change 0</td><td>Code and symmetry control with the semantic channel disabled.</td></tr>
<tr><td>Explicit same-group preference, 0 → 0.7</td><td>{fmt(effect('identity','choice_excess'))} percentage points in same-group choice excess</td><td>An assumed preference changes behavior. It was supplied, not discovered.</td></tr>
<tr><td>Memory on versus off</td><td>{fmt(effect('memory','cooperation'))} percentage points in cooperation</td><td>Remembering successful partners supports repeated cooperation under these rules.</td></tr>
<tr><td>Small counterbalanced behavioral differences</td><td>{fmt(effect('behavior','choice_excess'))} percentage points in choice excess</td><td>No clear marginal effect here; this narrow trait set does not exhaust possible behavior.</td></tr>
<tr><td>Combined stress, full model versus paired no-stress</td><td>{fmt(next(r for r in components if r['component']=='combined' and r['metric']=='cooperation'))} percentage points in cooperation</td><td>Resources, available options, and information all matter.</td></tr></table>
<p>Intervals are descriptive 95% bootstrap intervals across <strong>12 independent seeds</strong>, with matched conditions averaged within seed. Thousands of trajectories are not thousands of independent experimental units. The intervals cover sampling variability across simulation seeds with the model's assumptions held fixed.</p>
{image('factorial_effects','Marginal factorial effects during rounds 41–80. Discovery and independent replication agree closely. Other modeled factors are averaged with equal weight.')}
<h2>Stress did not simply “freeze the tribes”</h2>
<p>In the full model, cooperation fell from 83.94% in the matched no-stress condition to 65.51% during stress. Same-group choice above its available-partner share fell from 16.76 to 7.26 percentage points. Fewer visible candidates constrained the expression of an unchanged identity preference; an opportunity adjustment does not remove that constraint. The component tests identify which implemented changes produced these effects.</p>
<p>Rigidity is an explicit adaptation variable driven by unsuccessful interactions. It rose during stress. In the last ten recovery rounds, the residual rigidity difference was {fmt(rec(1,'late_rigidity_difference'),1)} with memory and {fmt(rec(0,'late_rigidity_difference'),1)} without it. Same-group choice had no clear late residual difference. This is <strong>temporary persistence within 40 recovery rounds</strong>, not proof of permanent group rigidity or hysteresis.</p>
<p>Only 5 of 72 memory-enabled pairs met the strict joint recovery rule by round 120; 44 of 72 did so without memory. The rule requires two consecutive ten-round blocks within 0.03 of the paired no-stress condition for both rigidity and choice excess. These pairs are clustered within twelve seeds. The horizon was too short to estimate unrestricted mean recovery time; censored cases remain censored.</p>
{image('recovery','Paired full-model trajectories. Gray marks the stress interval. Bands are pointwise 95% seed-bootstrap intervals, not simultaneous bands.')}
<details><summary>Stress components, population size, and parameter sensitivity</summary>
{image('stress_components','Scarcity, time pressure, and limited information were also switched on separately. Combined effects need not equal their sum.')}
{image('population_topology','Stress contrasts across simulated population sizes, network arrangements, and group balances.')}
{image('sensitivity_semantics','Left: memory-retention and scarcity sweep. Right: the same assumed dislike assigned to each label in turn.')}</details>
<h2>Smoke, exclusion, and alliances</h2>
<p>Smoke had no special causal status when words were inert. Assigning any label an avoidance coefficient of −0.7 reduced nominations to that label; targeting Smoke reduced incoming choices by 0.421 per member per round [0.383, 0.463]. Comparable effects appeared when each other label was targeted. This measures the response to the assigned avoidance coefficient.</p>
<p>A separate fictional attribution exercise gives all six labels identical failure evidence. Adding a prior favoring blame creates excess blame by construction. Neither that assay nor the cooperation model discovers scapegoating. In the full model, the combined-stress change in ten-round nonselection was small and its interval included zero. Forty-round cooperation networks remained connected in the main factorial runs. Strong reciprocal cross-group ties were measured as <em>alliance proxies</em>; no coalition bargaining or intent was modeled.</p>
<h2>Does leadership belong to a person or the arrangement?</h2>
<p>Identical agents on a regular ring had equal copying-response influence. Random and hub arrangements generated unequal scores. Exchanging the highest- and lowest-scoring identities left site scores unchanged for identical agents: the score moved with the site. This is a controlled symmetry demonstration, much like the earlier project's positional influence control. A separate assay added individual attraction and moved it with the individual.</p>
<p>The defensible answer is conditional: <strong>arrangement alone can create unequal influence in this model; individual differences can also matter when supplied.</strong> The copying-response score measures propagation under the specified update rule. One exploratory ring-network modularity null had a small negative interval excluding zero; the opportunity-adjusted random-choice null included zero. These finite-seed, multiple-diagnostic fluctuations do not overturn the exact lexical invariance control.</p>
{image('network_diagnostics','Additional post-analysis diagnostics. Left: observed group modularity relative to randomly reassigned memberships. Right: inequality in a specified eight-step copying response.')}
<h2>What remains proposed</h2>
<p>The optional group-decision game is a separate proposal for volunteers and has not been run or registered. Its protocol specifies consent, neutral and evocative labels plus a hidden-group control, session-level randomization, a displayed-history manipulation, mild resource/time constraints, outcomes, exclusions, analysis, debriefing, and a fixed stopping rule. Behavioral-role and affiliation-change modules are future extensions. Longer recovery, alternate learning rules, and empirical calibration are also future work.</p>
<p><strong>Checks:</strong> 12 unit tests passed; 18 selected trajectories reproduced exactly; all resource, group-accounting, source-hash, and saved-result checks passed. The simulation plan was saved before the ensemble. Detailed analysis and the additional diagnostics were developed afterward, so this report is exploratory, not a retrospectively claimed preregistration.</p>
<footer>Sources: <a href="https://doi.org/10.1002/ejsp.2420010202">Tajfel et al. (1971), arbitrary categorization</a>; <a href="https://doi.org/10.1103/PhysRevE.67.026126">Newman (2003), assortative mixing</a>; <a href="https://jasss.soc.surrey.ac.uk/23/2/7.html">Grimm et al. (2020), documenting agent-based models</a>. These motivate design and measurement; none calibrates this simulation.</footer>'''
    Path('report.html').write_text(page('SIMS: names, memory, and group boundaries',body),encoding='utf-8')
    Path('methods.html').write_text(page('Model and measurement specification',METHODS),encoding='utf-8')
    Path('human_protocol.html').write_text(page('Optional group-decision game — not executed',HUMAN),encoding='utf-8')
    print('Built report.html, methods.html and human_protocol.html.')


METHODS='''<div class="eyebrow">Technical protocol · Executed simulation</div><h1>Explicit assumptions, identifiable comparisons</h1>
<p><a href="report.html">Return to accessible report</a> · <a href="data/protocol.json">Pre-execution record</a> · <a href="data/tasks.json">Every configuration and seed</a></p>
<h2>Purpose and scope</h2><p>This agent-based study uses SIMS (simulated participants) to examine how interaction rules produce group patterns. Its parameters are chosen mechanism-test settings, and time is measured in model rounds. “Freeze,” “melt,” “disperse,” and “condense” describe increasing rigidity, decreasing rigidity, exploring contacts, and affiliation convergence, respectively. These terms describe measured changes in the SIMS' behavior; the six group names begin with identical rules.</p>
<h2>Design actually run</h2><table><tr><th>Family</th><th>Runs and identification</th></tr>
<tr><td>Core factorial C/D/E plus explicit identity mechanism</td><td>4,608 = 24 seeds × 3 topologies × 2 size balances × 2⁵ settings: trait differences, memory, combined stress, organizational adaptation, and same-group preference. N=60. The identity coefficient is 0 or 0.7; all other switches are off/on. Evocative labels have zero semantic coefficients.</td></tr>
<tr><td>A/B/name control</td><td>432 = 144 blocks × neutral names, evocative names, and a cyclic name permutation. Otherwise identical rules, h=0, no memory/stress/adaptation/trait differences. Unit tests also check name invariance with all mechanisms enabled except semantic perception.</td></tr>
<tr><td>Random interaction null</td><td>144 runs with uniform partner choice within the actual visible menu, no memory, no stress, no identity/semantic effects. It intentionally duplicates the homogeneous baseline numerically; it is an expectation control, not independent evidence.</td></tr>
<tr><td>Population sensitivity</td><td>288 runs: replication seeds, all three topologies and both balances, N=30/120, full model, paired stress/no-stress.</td></tr>
<tr><td>Stress ablations</td><td>216 runs: scarcity only, candidate restriction only, or information loss only; paired full-model core baselines reused.</td></tr>
<tr><td>Parameter sweep</td><td>432 runs: 12 replication seeds × 3 topologies × 3 memory retentions × (three scarcity levels under combined stress + one matched no-stress run). Equal groups. Retentions 0.85/0.97/0.995; pools 0.35/0.55/0.85.</td></tr>
<tr><td>Semantic sensitivity</td><td>324 runs: 12 replication seeds × 3 topologies × 9 cases. Coefficient −0.7 assigned to each of six labels, zero control, +0.7 for Smoke, and −0.7 with a cyclic label permutation. No learning, stress, adaptation, or trait differences; equal groups.</td></tr>
<tr><td>Later diagnostics</td><td>72 additional fixed-affiliation trajectories, each with 499 shuffled membership assignments, were added after the main analysis. Separate 144 influence assays and 288 synthetic attribution assays were executed by the main runner. Two full-model event-log exemplars and 18 verification reruns are reproducibility work, not extra independent evidence.</td></tr></table>
<h2>Entities, initialization, and counterbalancing</h2><p>An agent has a fixed network site, an affiliation g in {0,…,5}, persistent individual behavioral traits, a directed trust vector T, and rigidity r in [0,1]. There are no demographic categories or real-person attributes. All trust and rigidity begin at zero. Each run has 40 baseline, 40 intervention, and 40 recovery rounds; only stress-enabled runs receive the intervention.</p>
<p>Networks have exactly 3N undirected edges, no self-edges, and a connected ring backbone. Ring: degree six everywhere. Random: a degree-two ring plus 2N uniformly chosen missing edges. Hub: a degree-two ring plus 2N missing edges incident to three randomly selected sites. Thus “random” is not an unconstrained Erdős–Rényi graph. Sites are not spatial coordinates; mobility means contact exploration.</p>
<p>Equal groups have N/6 members. Unequal group counts use weights [0.35,0.25,0.15,0.10,0.10,0.05] on N−6 slots, add one guaranteed member to each, then distribute rounding remainders. At N=60, one rotation is [20,15,9,6,6,4]. Sizes rotate across group IDs. Agents are shuffled over network sites. Trait profile = (group + rotation + floor(rotation/6)) mod 6; twelve rotations in each seed split counterbalance labels with trait and size ranks, including every size-rank/trait pairing. This is exact marginal/rank counterbalancing, not exhaustive permutations of all individuals and graphs.</p>
<p>Profiles (holding tendency, exploration probability, generosity offset) are (0.65,0.10,−0.12), (0.50,0.12,0), (0.35,0.16,+0.12), (0.40,0.14,−0.06), (0.30,0.18,+0.06), (0.55,0.13,0). Identical agents use (0.45,0.14,0). Traits stay with an individual after affiliation changes; words never fix these traits.</p>
<h2>Per-round process and equations</h2><ol>
<li><strong>Candidate menu.</strong> Start with network neighbors. With probability exploration × (1−0.7r), add one uniformly drawn nonself contact. Uniformly sample up to six eligible candidates, or two under modeled time pressure. Every agent has at least two eligible partners. This is an option-budget surrogate for time pressure, not an explicit reaction-time model.</li>
<li><strong>Information.</strong> A per-agent visibility draw exposes remembered trust with probability 1 normally or 0.30 under limited information. Trust still updates from actual outcomes afterward. No misinformation is simulated.</li>
<li><strong>Choice.</strong> For each available j, choose with probability proportional to exp[1.6(1+0.5rᵢ)Tᵢⱼ × memory × visibilityᵢ + h·1(gᵢ=gⱼ) + b·1(labelⱼ=target)]. h is the explicit arbitrary-identity preference. b is zero outside semantic sensitivity. Neutral-name conditions disable the semantic channel. Uniform-choice null sets utility to zero.</li>
<li><strong>Cooperation.</strong> For request i→j, j cooperates with probability sigmoid[1.1 + generosityⱼ + 1.8·memory·Tⱼᵢ·visibilityⱼ + 1.2(pool−1)]. There is no group or word term in this decision. Pool=1 normally and 0.55 under core scarcity. The lower willingness under scarcity is a declared cost heuristic; it is not an emergent finding about real people.</li>
<li><strong>Allocations.</strong> Each recipient j divides its pool equally among successful incoming requests. Requester i receives pool / successful requests to j if j cooperates, otherwise zero. Unused pools are not carried forward. Total allocations cannot exceed N×pool. This is a replenished token allocation game, not an accumulated wealth economy or reciprocity bargaining game.</li>
<li><strong>Memory.</strong> Multiply all trust entries by retention (default 0.97). For the chosen partner update Tᵢⱼ ← Tᵢⱼ + 0.30[(2·success−1)−Tᵢⱼ]. Memory-off agents do not learn. Partner recognition is perfectly stable in the simulation.</li>
<li><strong>Organization.</strong> If enabled, update rᵢ ← rᵢ + 0.08[(1−success)−rᵢ]. After a successful cross-group request, switch to that partner's pre-switch affiliation with probability 0.06(1−rᵢ)(1−holdingᵢ). All switches are simultaneous. More failures raise rigidity by assumption; the experiment measures persistence and downstream effects of that assumption. Off means r=0 and fixed affiliation. State effects on exploration, trust-weighting, and switching are bundled; they are not individually identified.</li></ol>
<p>Independent initialization and round-random streams are derived from seed, population, and fixed stream IDs. Every round consumes draws of the same shapes even if a mechanism is disabled. Paired runs share exogenous draws, but treatment can change subsequent networks of interactions. Runs with different N are not trajectory-matched at the agent level.</p>
<h2>Outcome definitions</h2><table><tr><th>Outcome</th><th>Definition and limitation</th></tr>
<tr><td>Partner choice and cohesion</td><td>For each request, qᵢ = fraction of visible candidates sharing the requester's current affiliation. Choice excess = mean[1(chosen same)−qᵢ]. Both within- and cross-group candidate counts enter. This removes unequal marginal opportunity shares, not differences in menu diversity or unobserved human preferences.</td></tr>
<tr><td>Cooperation adjusted for opportunity</td><td>Within score = successful same-group requests / sum qᵢ; between score = successful cross-group requests / sum(1−qᵢ); gap = within−between, averaged over rounds. Scores can exceed one: they are opportunity-normalized event rates, not conditional probabilities. Conditional cooperation after same/cross choice is also saved, but choice selection can confound that comparison.</td></tr>
<tr><td>Allocations and crossings</td><td>Received amounts split by within/between contacts and divided by the same opportunity denominators; cross-group chosen fraction; fraction switching affiliations per round. Per-label nominations and receipts use contemporaneous member-round denominators to handle changing sizes.</td></tr>
<tr><td>Network assortativity and modularity</td><td>Within each 40-round phase, Wᵢⱼ counts successful requests i→j. Directed mixing matrix e aggregates W by <em>phase-end</em> affiliation and sums to one. Q = trace(e)−dot(outgoing marginals,incoming marginals); assortativity = Q/(1−expected). Q is modularity of the supplied affiliation partition, not optimized community modularity. The contemporaneous group-pair cooperation and opportunity matrices are separately saved.</td></tr>
<tr><td>Alliance proxies</td><td>For each cross-group pair use the minimum of its two directional contemporaneous cooperation/opportunity rates. Rank the top three reciprocal pairs and measure overlap between phases. Ranks do not establish statistically exceptional cooperation, strategic coalitions, or intention; arbitrary ties and small exposure can matter. The CSV retains descriptive strength and persistence.</td></tr>
<tr><td>Exclusion and fragmentation</td><td>Ten-round nonselection = fraction receiving no successful incoming request in that window; average the four nonoverlapping windows per phase. This is a network-isolation proxy, not intentional exclusion. Forty-round nonselection is also saved. Fragmentation = 1−largest weak component/N; also save number of components. Graphs ignore edge direction for components.</td></tr>
<tr><td>Influence and hierarchy</td><td>Let P=0.5I+0.5 row-normalized W (isolated rows retain themselves). Equal unit perturbations under hypothetical copying x(t+1)=Px(t) have influence v=(1/N)1ᵀP⁸. Save Gini(v), max(v), group shares, and maximum group share minus population share. This is an eight-round linear-response proxy, not actual opinion propagation during the game or leadership validation.</td></tr>
<tr><td>Recovery and rigidity</td><td>Paired full-model stress/no-stress difference in rigidity and choice excess. Recovery requires two adjacent ten-round recovery blocks each within ±0.03 on both measures; first eligible endpoint 20, then 30 or 40 rounds after stress. Censor at 40 if absent. Report recovery fractions and mean min(T,40), never treat censoring as an observed recovery. Threshold and analysis were selected after execution, before numerical inspection; they are exploratory. The last ten rounds provide a separate persistence estimate.</td></tr>
<tr><td>Blame sensitivity</td><td>Separate synthetic vignettes have equal failure evidence for every label. Six-category probabilities proportional to exp(bias×target indicator), with bias 0 or +0.7; 600 draws per seed/target/bias, 24 seeds. Only the assumed attribution prior produces an excess. This task does not interact with the cooperation model and includes no real people.</td></tr></table>
<h2>Influence interventions and causal limits</h2><p>The separate influence assay uses the fixed initial opportunity graph, not the learned cooperation graph. Identical-agent response scores are computed as above. Select highest/lowest site and swap their occupant identities. For identical agents, site invariance is algebraically guaranteed: it is a symmetry audit, not independent evidence for leadership. A second case gives individuals fixed Normal(0,0.25²) attraction; each receiving column of the graph is weighted by exp(attraction). Attraction moves with the swapped individual. Its contribution is conditional on this chosen copying law. Ring ties make any single argmax identity arbitrary; do not interpret ring leader turnover.</p>
<p>Factorial contrasts compare mechanism settings within the same randomized seed/topology/balance block and average all other settings equally. They identify effects of changing <em>this program's</em> rules. Stress components are separate matched interventions. Size comparisons also change relative network sparsity; no isolated “pure population” cause is claimed. Hysteresis would need longer recovery, repeated loading/unloading, and matched steady states; it was not established here.</p>
<h2>Analysis, uncertainty, and validation</h2><p>Discovery seeds 1100–1111 and independent replication seeds 9100–9111 were fixed before execution. No fitting or prediction training was performed; “discovery” is a split label, not a source of tuned parameters. Both batches were executed before numerical analysis. Primary bootstrap intervals resample the twelve seed-level contrasts 10,000 times after averaging topology and balance within seed. They are unadjusted descriptive intervals; multiple outcomes are exploratory. Curves use 2,000 resamples and pointwise bands. Full factorial main effects, stress×memory/identity/adaptation interactions, component contrasts, size/topology strata, parameter sweeps, and every phase-level outcome are exported.</p>
<p>Nulls include exact lexical permutation invariance, uniform interaction expectations, no-stress trajectories, and an additional 499-shuffle fixed-affiliation modularity null per diagnostic trajectory. The latter reassigns membership across individuals while preserving group counts; it is distinct from merely renaming whole groups. Its tail fraction is a descriptive diagnostic under that exchangeability null, not an adjusted p value from volunteer data.</p>
<p>Tests cover resource conservation, known graph modularity, no self-choice, stable frozen affiliation, reproducibility, stress-free baseline equality, semantic-channel necessity, opportunity adjustment, balanced sizes, equal topology edge counts, and copying-response symmetry. Verification also independently sums group-pair outcomes, checks every pool bound and influence total, verifies frozen source hashes, and reproduces eighteen selected trajectories.</p>
<h2>Saved artifacts and provenance</h2><p><code>data/tasks.json</code> gives every input. <code>data/arrays.npz</code> stores trace, phases, groups, pairs, and event digests; <code>data/schema.json</code> names the columns. Row order matches tasks.json. Trace shape is runs×120×fields; phases is runs×3×fields; groups is runs×18×fields (phase-major); pairs is runs×108×fields (phase, source, destination). NaN marks undefined ratios or unsampled window metrics, not zero. Full event logs are saved for two representative paired runs; other trajectories are reproducible from inputs and checked event digests.</p>
<p>The project was inspected at commit <a href="https://github.com/NousVolition/My-Sources-Project-ALL/tree/277157c4f44d33a0d4eba29b60bcf2104e28a46a">277157c4f44d33a0d4eba29b60bcf2104e28a46a</a>. Relevant context: <a href="https://github.com/NousVolition/My-Sources-Project-ALL/blob/277157c4f44d33a0d4eba29b60bcf2104e28a46a/reports/water-molecule-influence/README.md">positional influence among identical water molecules</a> and the <a href="https://github.com/NousVolition/My-Sources-Project-ALL/blob/277157c4f44d33a0d4eba29b60bcf2104e28a46a/reports/molecular/isotope-mass/README.md">isotope-mass experiment</a>. Those studies provide context for the identity-versus-position question; the SIMS results are generated by the interaction rules specified here. The earlier “Hénon Escape Behavior” conversation was read; inaccessible content-reference placeholders were not reconstructed.</p>
<p>This package is published in <code>NousVolition/Nous-Volition</code> (Streams and Rocks), under <code>studies/social-organization/</code>, at the user's requested destination. The earlier My-Sources-Project-ALL study remains research context. See README.md for commands.</p>
<footer>Documentation structure follows the purpose, entities, process, design concepts, initialization, input, and submodels approach of <a href="https://jasss.soc.surrey.ac.uk/23/2/7.html">Grimm et al. (2020)</a>; network mixing definitions follow <a href="https://doi.org/10.1103/PhysRevE.67.026126">Newman (2003)</a>.</footer>'''


HUMAN='''<div class="eyebrow">Optional group-decision game · Draft for preregistration · Not executed</div><h1>Optional group-decision game</h1>
<p class="lead">A proposed volunteer activity about arbitrary identities, words, and remembered interactions.</p>
<p class="note"><strong>Status:</strong> No recruitment, consent, participant data, ethics approval, or external registration exists for this protocol. The simulation results above are already known. This prospective volunteer protocol must be dated and registered before collecting its confirmatory sample; the investigator, venue, ethics determination, compensation amount, and data-retention period must be filled in first.</p>
<p><a href="report.html">Return to simulation report</a>. This design separates arbitrary categorization from the meaning of words, and tests mild constraints without threats or real social exclusion.</p>
<h2>Research questions and hypotheses</h2><ol>
<li><strong>Arbitrary identity:</strong> Do visible neutral group labels increase available-partner-adjusted same-group choice compared with undisplayed random group assignments?</li>
<li><strong>Label semantics:</strong> Do evocative labels change this outcome relative to neutral labels when task rules, colors, positions, and opportunities are held equivalent? Smoke-specific nominations are a prespecified secondary contrast, not a premise that Smoke is disliked.</li>
<li><strong>Constraints:</strong> Does a mild, reversible resource/time manipulation alter cooperation and group-boundary measures compared with a matched no-stress schedule? Direction is two-sided; the simulation's direction is not assumed to hold for humans.</li>
<li><strong>Displayed history:</strong> Does access to one's recent interaction record change cooperation and recovery? This manipulates an external memory aid; it cannot turn a person's memory off.</li></ol>
<h2>Participants, fixed sample, and stopping rule</h2><p>Adults aged 18 or older who can give informed consent and understand the study language; recruit without selecting political, ethnic, religious, or other real-world identities. Exclude participation in another session of this study. Run a separate usability pilot of four sessions of 30 adults (N=120). Pilot data are never pooled with confirmatory outcomes. Use the pilot only to verify comprehension, timing, accessibility, and technical reliability; any design changes require an amended preregistration before the confirmatory cohort.</p>
<p>The proposed confirmatory budget is <strong>72 sessions × 30 participants = 2,160 adults</strong>, six independent sessions per factorial cell. This is a planning choice, not a power guarantee. Stop at 72 completed, technically valid sessions, with at most 12 replacement sessions for the technical failures defined below. No stopping based on effect size, p values, label patterns, or interim hypothesis results. If recruitment or funding ends earlier, report the shortfall and analyze the achieved sample without calling it the planned study.</p>
<p>Power planning must use sessions as independent units. At an assumed session-outcome SD of 0.10, a neutral-versus-evocative marginal comparison with 24 sessions per level has SE≈0.0289. A conservative two-sided α=0.0125 threshold and 80% power gives an approximate detectable difference of 0.096. This normal approximation is illustrative, not an executed or validated power analysis. If that sensitivity is inadequate, increase the fixed session count in multiples of 12 <em>before</em> preregistration; do not extrapolate human power from the agent simulation.</p>
<h2>Randomization and design</h2><p>Session-level 3×2×2 factorial: displayed identity (hidden random groups / neutral Group 1–6 / Ice, Water, Fog, Mist, Gas (water vapor), Smoke), constraint schedule (no constraints / reversible constraints), and history display (off/on). Twelve cells, six sessions each. Randomize cells within recruitment batches using a concealed computer-generated schedule; record the seed and allocation file before recruitment. Prevent treatment spillover by running each session privately and prohibiting cross-session discussion during testing. Analyze assignment, regardless of participants' inferred identities.</p>
<p>Assign five members to each of six arbitrary groups uniformly at random, independently of seat, participant ID, and opportunities. In the hidden condition, keep the same latent memberships only for analysis; show no group badge. Rotate names across internal group IDs with a six-order Latin schedule within each factorial cell. Use identical typography and grayscale badges. Randomize menu positions every round. No adjectives describe the labels, and no facilitator calls Smoke dirty, dangerous, or an outsider. Groups have identical task rules and endowments in the core study.</p>
<h2>Procedure and tasks</h2><ol>
<li><strong>Consent and practice, about 10 minutes.</strong> Explain arbitrary assignments, token tasks, mild time limits, recording, fixed payment, optional questions, and the right to withdraw. Give two private practice rounds and a comprehension check. Provide two explanation retries; anyone who still does not understand leaves with the promised base payment and is excluded before session assignment.</li>
<li><strong>Baseline, rounds 1–10.</strong> Each participant sees six eligible partners sampled uniformly without self-choice, chooses one, and decides whether to contribute one virtual token to that partner. Every participant makes at most one outgoing contribution per round. Keep identities stable across rounds. Record all menus; never fabricate choices or partner outcomes. Use a fixed 20-second decision window for both decisions together. If history is on, show the participant's own actions and received contributions from the last three rounds; if off, omit that panel. All participants see their actual current-round result. No public reputations or rankings.</li>
<li><strong>Manipulation, rounds 11–20.</strong> Constraint sessions use six task tokens instead of ten and an eight-second decision window. Controls retain ten tokens and twenty seconds. Tokens have no effect on guaranteed compensation and cannot create debt or loss of personal property. Candidate menus remain six items, so time pressure is not confounded with menu size. No threat, competition for payment, deception about emergencies, or public penalties. Timeouts are recorded as omissions, never recoded as rejection.</li>
<li><strong>Recovery, rounds 21–40.</strong> Restore ten tokens and twenty seconds in all sessions. Keep history assignments unchanged. Retain everyone in the game and permit a pause or withdrawal at any point. This is an experiment about recovery after constraints, not inducing distress.</li>
<li><strong>Private allocation task.</strong> At rounds 10, 20, 30 and 40, allocate ten purely experimental tokens among six presented partners (one from each latent group, uniformly sampled; no self). The hidden condition displays only IDs. Record the full choice set. Present instructions identically across conditions.</li>
<li><strong>Private ratings and debrief, about 5 minutes.</strong> Rate clarity, effort, perceived time pressure, and label familiarity/pleasantness after the behavioral task to avoid semantic priming. Skip options are allowed. Explain the arbitrary assignments and the actual hypotheses, and stress that no group has an intrinsic moral or personal meaning.</li></ol>
<p><strong>Frozen game rule:</strong> Each round starts with ten virtual tokens per participant (six during the constraint interval). Contributing one token costs the donor one token and credits the chosen recipient two virtual points. Retained tokens count as one point each. Thus round score = initial tokens − contribution + 2 × number of received contributions. Multiple incoming contributions add independently and require no response, so every person faces the same number of decisions. Points reset each round and have no monetary conversion; only the current score and incoming contributor IDs are shown privately. Choosing a partner and contributing zero is a valid decision. A timeout or skip has no transfer and is recorded as missing decision, not zero cooperation. This prospective human game differs from the simulation's recipient-response game; it tests the mechanisms rather than claiming an exact human replication. There are no fake messages or concealed penalties.</p>
<h2>Separate semantics and fictional attribution module</h2><p>Optional, separately preregistered semantic pilot: 120 different consenting adults rate all six words in randomized order for valence, familiarity, and expected behavior; include neutral group names as anchors. Do not preselect a disliked label after seeing results. Confirmatory Smoke contrasts stay two-sided. Semantic ratings are measured moderators, not randomized causes of behavior.</p>
<p>Optional safe attribution task: show a fictional six-team scheduling vignette with exactly equal error counts and exposure for all six teams. Randomly assign word-to-team mappings, balance order, and ask how responsibility for the fictional delay should be distributed. State explicitly that all teams are fictional; no participant receives blame or sees others' ratings. Primary attribution outcome is deviation from the evidence-based equal share, with the Smoke-minus-other-label contrast compared against its neutral counterpart. Analyze as a separate family with multiplicity control. Do not present blame vignettes before the core interaction task.</p>
<h2>Primary outcomes and analysis</h2><p>Primary outcome 1: each participant-round's same-group choice indicator minus the fraction of available candidates sharing that participant's current arbitrary membership. Compute participant means, then the session mean over rounds 11–20. Hidden-condition membership is a latent randomized analysis grouping. Report the same statistic in baseline and recovery. Primary outcome 2: proportion of eligible cooperative decisions with contribution, excluding technical missingness from denominators and reporting omissions separately.</p>
<p>Four prespecified confirmatory contrasts: neutral minus hidden on outcome 1; evocative minus neutral on outcome 1; constraint minus control on outcome 2; history display minus no history on outcome 2. Use session-level factorial regression with display indicators, constraint, history, all two-way interactions and their three-way terms, and recruitment-block indicators. Estimate marginal contrasts with equal weight over the other randomized factors. Use studentized randomization inference (10,000 allocations preserving the original blocked factorial schedule), with two-sided tests; report randomization-compatible or session-bootstrap confidence intervals. Apply Holm correction across the four primary tests at familywise α=0.05. Report adjusted and raw p values and effect sizes.</p>
<p>Secondary outcomes: conditional within/between cooperation, available-partner-adjusted allocations, switching if enabled only in a later module, group nomination and response shares, label-specific nominations (including Smoke), assortativity/Q, weak components, ten-round nonselection, reciprocal alliance proxies, and recovery. Test planned label contrasts in a separate Holm-adjusted family; all other secondary results are explicitly exploratory. Repeated rounds, six groups, or thirty people are not independent session replicates. Cluster by session in all auxiliary individual-level models. Report both effect estimates and uncertainty, including null or reversed effects.</p>
<p>Human recovery endpoint: subtract each session's baseline mean, then compare constrained and control sessions in each five-round recovery block. Recovery occurs at the second of two consecutive blocks whose <em>estimated group difference</em> lies within ±0.05 on both primary outcomes; require a confidence interval wholly inside the band for an equivalence claim. This population-level endpoint differs from the simulation's paired-trajectory rule. Report unresolved recovery at round 40 as censored, not permanent rigidity. The timeline and confidence intervals remain primary evidence if the threshold is not met.</p>
<h2>Missingness, exclusions, and integrity</h2><p>Analyze all randomized sessions with usable outcome logs. Exclude a session only for pre-documented platform failure that loses more than 20% of round records or reveals another condition's instructions; report its assignment and reason and retain a sensitivity analysis where possible. Replace it using the next allocation in the prespecified reserve schedule. Do not exclude a session because groups are uncooperative, labels are disliked, an effect reverses, or manipulation ratings are low.</p>
<p>Withdrawn participants contribute data only as permitted by consent and their deletion request. For retained data, analyze observed eligible opportunities and report denominators by condition. Record timeout, skip, withdrawal, and network failure as distinct events. Do not impute cooperation or hostility from missing responses. Report worst/best-case bounds for differential omissions, and flag substantial differential attrition as an identification limit. No inferential hypothesis inspection until the data freeze; technical monitoring may inspect logs without treatment labels.</p>
<h2>Consent, safeguards, and debrief language</h2><p><strong>Suggested consent text:</strong> “You are invited to a study of decisions in small groups. Group assignments and names are random. You will choose partners and allocate experimental tokens. Some rounds have shorter decision times or fewer tokens. These tokens do not affect your guaranteed payment. You may skip optional questions, pause, or stop without penalty. We record game decisions and timing under a study ID. We will explain the study afterward. Please ask any questions before deciding whether to participate.” Add duration, contact, exact payment, privacy details, withdrawal/deletion process, and institutional information before use.</p>
<p><strong>Suggested debrief:</strong> “The study tests whether arbitrary group names, access to past interactions, and mild task constraints affect decisions. No label describes your personality or any real-world community. All groups followed the same core rules. There were no real threats, and no group was assigned to be bad or deserving of blame. Any differences describe this particular task and do not rank people or groups.”</p>
<p>Obtain the appropriate independent ethics review or formal determination before recruitment; this document does not declare exemption. Use accessible timers, a pause option, private screens, and a neutral facilitator. Store only necessary pseudonymous events; keep consent/payment contact details separate. Do not collect protected demographic traits unless independently justified and consented. Define access controls and a retention/deletion date before registration. Share aggregated or carefully de-identified data, not a publicly identifiable social network. Follow the consent principles described by <a href="https://www.hhs.gov/ohrp/regulations-and-policy/guidance/faq/informed-consent/index.html">OHRP</a>; requirements depend on the actual institution and jurisdiction.</p>
<h2>Behavioral roles, switching, and leadership: future modules</h2><p><strong>C, roles:</strong> Randomize small differences in allowed partner reach, decision revision, or tie duration, counterbalanced across all six labels using Latin schedules. Cross role differences with label display; show the actual rules clearly. Separate each rule from any reputation description. Prespecify within-role label contrasts and between-role contrasts; do not infer a word effect from an assigned rule.</p>
<p><strong>D, uncertainty:</strong> In a separate factorial module randomize disclosure of objective task information, keeping time and tokens fixed. Announce any missing information accurately; no false threats or fake majority opinions. Compare information-only, time-only, resource-only, and combined constraints against matched controls.</p>
<p><strong>E, affiliation:</strong> Randomize optional, costless affiliation switching versus fixed groups; keep names and people distinct from organization. In the switching condition permit a private change after rounds 10, 20 and 30, including “no group.” No forced rejection or public expulsion. Record available destinations and exposure; assess whether earlier conditions predict voluntary retention after recovery.</p>
<p><strong>Leadership:</strong> Randomize communication positions independently of label and participant, then rotate positions between blocks while keeping task information and opportunities otherwise matched. Compare nominations, actual uptake of suggestions, and success; add a separate ability measure obtained before assignment. This permits a test of position effects and conditional individual differences. It cannot equate a simulation centrality score with human authority.</p>
<p>These modules need their own fixed sample sizes, randomization schedules, outcomes, multiplicity families, and preregistrations; they are proposals, not completed experiments or implied parts of the 72-session core.</p>
<footer>Design background: <a href="https://doi.org/10.1002/ejsp.2420010202">Tajfel et al. (1971)</a> for arbitrary categorization; <a href="https://www.cos.io/initiatives/prereg">Center for Open Science preregistration guidance</a> for prospective commitments. Complete the listed administrative fields, verify the implementation against these rules, and attach the randomization schedule before registering this protocol.</footer>'''


if __name__=='__main__':main()
