"""Report the executed transient-memory addendum without modifying frozen results."""
import json
from pathlib import Path


def section(figure):
    r=json.loads(Path('data/transient_memory.json').read_text())
    def value(family,condition,metric,split='replication'):
        return next(q for q in r['summaries'] if (q['family'],q['condition'],q['metric'],q['split'])==(family,condition,metric,split))
    def estimate(family,condition,metric,scale=1):
        q=value(family,condition,metric)
        return f"{q['mean']*scale:.4g} [{q['lo']*scale:.4g}, {q['hi']*scale:.4g}]"
    rows=[]
    for c in ('directed','reverse','symmetric','uncoupled'):
        q=value('sequence',c,'transitions');f=value('sequence',c,'forward_fraction');b=value('sequence',c,'reverse_fraction')
        pct=lambda a:'not defined (no transitions)' if a['mean'] is None else f"{100*a['mean']:.0f}%"
        rows.append(f"<tr><td>{c}</td><td>{q['mean']:.2f} [{q['lo']:.2f}, {q['hi']:.2f}]</td><td>{pct(f)}</td><td>{pct(b)}</td></tr>")
    return f'''<h2 id="transient-memory">Temporary states, switching routes, and memory</h2>
<p class="lead">A system can lose sensitivity to its starting activity while preserving a separate record of earlier input. Those are different tests, and the full state must include that record.</p>
<p>The two newer screenshots are from Hildegard Meyer-Ortmanns's <a href="https://www.frontiersin.org/journals/network-physiology/articles/10.3389/fnetp.2023.1276401/full">Heteroclinic networks for brain dynamics (2023)</a>: the framework paragraph and Figure 2. The paragraph's “Rabinovich et al., 2015a” is <a href="https://pubmed.ncbi.nlm.nih.gov/26149511/">Rabinovich, Simmons and Varona, Dynamical bridge between brain and mind</a>.</p>
<h3>Reading Figure 2: the same states, different temporal organization</h3>
<p>The nine vertices represent saddle states in a system's state space. An arrow represents a possible trajectory connecting states; it is not necessarily a physical wire between individual neurons. Orange cycles emphasize different groupings in panels A and B. The caption gives these possible sequences:</p>
<table><tr><th>Panel</th><th>Successive groups of visited states</th></tr><tr><td>A</td><td>(1, 2, 3) → (6, 4, 5) → (8, 9, 7)</td></tr><tr><td>B</td><td>(1, 4, 7) → (8, 2, 5) → (6, 9, 3)</td></tr></table>
<p>The vertex set and available connections can be the same while the attracting route changes. Rates of expansion and contraction near saddles, inputs, and parameters matter; an unlabeled graph alone does not determine the timing or preferred path. This is a concrete way that organization can reside in relations and temporal order. It does not imply that individual properties never matter.</p>
<p>The figure refers to <a href="https://arxiv.org/abs/2112.12642">Thakur and Meyer-Ortmanns (2022)</a>, whose model explores entrainment of such sequences. Their work finds dependence on coupling, placement, and unit parameters. Our earlier oscillator-SIMS placement test and the following six-mode test are separate models; neither reproduces their nine-saddle system. An exact reconstruction of Figure 2 has <strong>not</strong> been run here.</p>
<h3>Reading Figure 5: the route propagates through an arrangement</h3>
<p>The next supplied figure is Figure 5 of the same review. It displays one pacemaker at chain position 1 and 15 driven units, each capable of the nine-state dynamics. Horizontal position is time; vertical position is the unit's place in the chain; color identifies the active pattern among nine possibilities. The colors are not the six Ice/Water/Fog/Mist/Gas/Smoke labels.</p>
<p>A vertical color band indicates that the units visit the same pattern at the same time at the displayed resolution. In the left panel, successive shades occur within broader color groups; in the right panel, the route repeatedly crosses those groups. These panels correspond to the alternative routes in Figure 2. The time windows differ, so their apparent stripe widths alone do not establish a frequency ratio.</p>
<p>The pacemaker is assigned in the model. The figure demonstrates the reported transmission of a temporal pattern through coupling; it does not establish that authority arose spontaneously, that every internal variable is identical, or that the pattern encodes measured human thoughts. To test individual versus arrangement, a future matched experiment would swap the pacemaker's intrinsic parameters and its position separately while measuring sequence agreement, time lag, and recovery. Our earlier oscillator placement experiment tests a related question with different equations; this exact chain has not been simulated here.</p>
<h3>Dissipation does not guarantee forgetting</h3>
<p>Bounded or volume-contracting dynamics need not bring every starting state to the same trajectory. A simple counterexample is ẋ=x−x³, ẏ=−2y: its divergence is −1−3x²&lt;0 everywhere, yet it has two attracting equilibria, (+1,0) and (−1,0). The sign of the starting x selects the destination. Thus rapid loss of starting-state information requires a separate convergence test under a specified input.</p>
<p>In the heteroclinic approach, a trajectory can approach a saddle along contracting directions and depart along an expanding one. Temporary residence can therefore coexist with continued switching. <a href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000072">Rabinovich and colleagues (2008)</a> develop this mechanism using stable heteroclinic channels. Observing a sequence of peaks alone is insufficient to prove such a channel.</p>
<h3>What the new SIMS model assumes</h3>
<div class="equation">ẋᵢ=xᵢ[1+uᵢ+g mᵢ−ΣⱼRᵢⱼxⱼ]+ε,<br>ṁᵢ=(uᵢ−mᵢ)/τ, &nbsp; i=1,…,6.</div>
<p>xᵢ≥0 is an abstract activation level; uᵢ≥0 is input; mᵢ is a fading input trace. These six modes are neither six measured neurons nor the six social groups. Rᵢⱼ is inhibition of receiver i by sender j. The constant growth drive and input support activation, but this is not a calibrated excitatory/inhibitory neural circuit. There are no learned weights, spikes, molecular phases, or physiological units.</p>
<p>The directed baseline sets Rᵢᵢ=1, Rᵢ₊₁,ᵢ=0.7 modulo six, and all other entries to 1.6; ε=0.001 and τ=30. Each active mode suppresses its designated successor less than the others. The order is therefore <strong>encoded in the arrangement</strong>. Reversing R transposes it; the symmetric control uses (R+Rᵀ)/2; the uncoupled control uses the identity. Renaming modes has no dynamical effect; a whole-coordinate permutation check also passes.</p>
<p>With ε=u=m=0, each coordinate-axis state with one xᵢ=1 is a saddle with eigenvalues −1, +0.3, and four copies of −0.6. Our executed ε&gt;0 model moves away from those exact axis equilibria. Its peaks are reported as <em>temporary dominance episodes</em>; formal metastability, structural stability, and existence of a heteroclinic network for the perturbed model have not been proved.</p>
<p>Nonnegative initial states remain nonnegative in the continuous equations. For bounded input and trace, ẋᵢ≤xᵢ(B−xᵢ)+ε for a finite bound B, so activity cannot grow without bound. This supplies a bounded absorbing region, not global contraction: even the zero-input model's activity-space divergence is positive near the origin. The numerical solver never clips negative values.</p>
<h3>Executed design and results</h3>
<p><strong>{r['runs']} trajectories</strong> used 24 fresh seeds, split in advance into 12 discovery and 12 replication seeds; 22 conditions per seed; horizon 160; RK4 step 0.02; saved spacing 0.2. There are 480 distinct parameter-and-initial-state cases: 48 scheduled duplicate trajectories serve as matched/design controls. Two seeds across all 22 conditions were repeated at half the step. The largest state discrepancy was {r['maximum_half_step_difference']:.3g}. All nine numerical checks passed. An initial plotting-only failure was repaired and the same calculations rerun exactly; no parameters were tuned after seeing the results.</p>
<p>A dominant mode accounts for at least 70% of total activity for at least one model-time unit. Scores use time 20–160, discard shorter episodes, and collapse repeated winners across gaps. Dwell intervals touching an observation boundary are censored. Intervals below are descriptive 95% percentile bootstraps of 12 whole replication seeds, not independent time points or neural-population uncertainty.</p>
<table><tr><th>Connections</th><th>Mean detected transitions [interval]</th><th>Follow forward cycle</th><th>Follow reversed cycle</th></tr>{''.join(rows)}</table>
<p>Both discovery and replication followed the assigned direction in all detected baseline/reverse transitions. All six modes were visited in each baseline replication run. Their mean within-run median uncensored residence time was {estimate('sequence','directed','median_uncensored_dwell')} model units. The symmetric and uncoupled controls produced no detected transitions in replication. These are consequences of declared mechanisms, not evidence that a semantic identity causes switching.</p>
{figure('transient_switching','A declared replication seed under directed, reversed, symmetric, and externally cued conditions. The same fast initial state is used. Axes have different vertical ranges where the external input raises activity.')}
<p><strong>Input sensitivity:</strong> a cue of amplitude 2 targeted one mode during [80,100). Targets were balanced across all six modes. Compared with the matched no-cue run, the cued mode's activity share in [90,100) increased by {estimate('paired','cue_minus_none','target_fraction',100)} percentage points. All trajectories were exactly identical to their no-cue controls before the cue.</p>
<p><strong>Forgetting initial activity:</strong> two independently sampled fast states received the same sustained cue and identical initial traces, with memory feedback disabled. Their mean Euclidean separation at time 20 was {estimate('forgetting','clamp','distance_at_20')}, versus {estimate('forgetting','none','distance_at_20')} without a cue. By time 60, the cued pairs coincided to floating-point precision; this is not a proof of finite-time merging of exact continuous trajectories.</p>
<p><strong>Retaining input history:</strong> two past unit inputs of duration 30 prepared m₀=(1−e⁻¹)eⱼ for opposite modes. We deliberately reset the fast activity to the same value in both cases, then applied the same zero future input. With g=0.8, mean separation averaged over time 0–40 was {estimate('history','0.8','mean_distance_0_40')}; with the trace disconnected (g=0), it was exactly zero. This isolates the influence of stored input under the model. It is not learned recall, task accuracy, or proof that the retained information is useful.</p>
<p>The trace itself decays exactly as m(t)=m₀e⁻ᵗ⸍³⁰ after the input stops. At time 160 it is small, yet activity separation remains {estimate('history','0.8','distance_at_160')}: earlier input has shifted the phase of the later switching cycle. Decay of a trace does not necessarily reset the subsequent trajectory.</p>
<h3>The later excerpts: memory of a route through a branching network</h3>
<p>The two additional passages come from the same article's noise discussion. They distinguish a one-step Markov description from dependence on earlier visited states. If Sₙ records only the currently visited saddle label, a one-step Markov model requires:</p>
<div class="equation">P(Sₙ₊₁=k | Sₙ=j, Sₙ₋₁=i, …)=P(Sₙ₊₁=k | Sₙ=j).</div>
<p>Two trajectories near the same saddle can arrive at different offsets along its stable directions. If those offsets retain information about the incoming route, a later branch can depend on that route. In the excerpt's eigenvalue ordering λₛ₁&lt;…&lt;λₛₙ&lt;0&lt;λᵤ, the local saddle quantity is σ=λᵤ+λₛₙ: expansion competes with the weakest contraction. The discussed positive-σ “lift-off” displaces an outgoing probability distribution from the noise-free connection. Whether that displacement survives to affect another branch also depends on the rest of the network and the noise. The sign alone is not a general theorem of long-term memory.</p>
<p>This is memory in a reduced description. A full stochastic state driven by white noise may be Markovian while the sequence of observed saddle labels is not, because labels omit the within-neighborhood coordinates. Likewise, a deterministic ODE has a unique future from its full state under a fixed input. Finding dependence on previous labels does not contradict that. Non-Markovian behavior also does not by itself establish indefinitely persistent memory, learned recall, or useful task performance.</p>
<p>For a primary treatment of graph construction and history-dependent switching, see <a href="https://www.sciencedirect.com/science/article/pii/S0167278913002601">Ashwin and Postlethwaite, On designing heteroclinic networks from graphs</a>. Local eigenvalues must be interpreted with the global connections and the noise regime.</p>
<p><strong>Not yet executed:</strong> our six-mode model has no stochastic forcing, only one preferred successor per mode, and an explicit input trace. It cannot validate the excerpt's noise-induced branching mechanism. A suitable next experiment would use a declared branching network, vary stable/unstable eigenvalue ratios and noise amplitudes, and compare next-state predictions from current state alone against current-plus-previous state on independent held-out seeds. Time and external inputs must be matched; dwell times must be recorded separately. First-order Markov surrogates with matched visitation counts and the same analysis would check false detections. These comparisons would distinguish route dependence from finite-sample bias, changing inputs, or changing transition rates.</p>
<h3>The learning excerpt: can the arrangement itself be acquired?</h3>
<p>The final supplied passage describes a different level of memory: adapting interactions so that previously presented sequences can later be retrieved. It contrasts generalized associative-memory approaches with sequence learning through winnerless competition, then describes a driven template whose parameters adapt while following a teacher. This adds a question beyond our fixed-connection experiment: how could the connection arrangement develop from experience?</p>
<p><a href="https://www.frontiersin.org/journals/applied-mathematics-and-statistics/articles/10.3389/fams.2019.00063/full">Voit and Meyer-Ortmanns (2019), Dynamical Inference of Simple Heteroclinic Networks</a>, provide a primary model of inference under an assumed heteroclinic generating process. Matching an observed sequence alone does not uniquely identify its mechanism: distinct equations and connection strengths may generate similar outputs.</p>
<p><strong>Proposed, not run:</strong> compare a learner with adjustable connections against frozen and shuffled-sequence controls, using equal teacher input. Then remove that input and freeze learning before scoring sequence recall on held-out initial states, partial cues, and independent noisy trials. Following a teacher only while directly driven would demonstrate entrainment; persistent recall after that drive is removed would provide a stronger, model-specific test of storage. Parameter recovery should be scored separately from prediction and recall.</p>
<p>Our current R matrix never learns. Its order is assigned, and its m variables only filter past input. Neither that trace nor the observed switching is evidence that SIMS learned an organization. The social analogy remains a proposal for testing mechanisms, not a literal identification of social groups with neural populations or physical phases.</p>
{figure('transient_memory','Replication means distinguish starting-state separation from stored-input effects. Zero separation denotes floating-point agreement. The nine-condition sweep shows threshold-based transition counts, not a universal law of switching.')}
<p><strong>Sensitivity:</strong> successor inhibition 0.6, 0.7, 0.8 was crossed with activation floors 0.0001, 0.001, 0.01 using the same seeds. At floor 0.01 the 70% dominance detector found no qualifying transitions. That need not mean every oscillation disappears: the outcome depends on an explicit dominance definition. Noise robustness, alternative dwell thresholds, longer observation windows, multiple branching routes, and a biologically calibrated excitation/inhibition balance remain future tests.</p>
<h3>What this contributes to Streams and Rocks</h3>
<p>In this constructed model, changing only the interaction arrangement reverses the order of activity; an external cue can change which mode dominates; a stored trace can alter later timing. No individual mode is intrinsically the permanent leader. The result supports asking about <em>connections, input, history, and timing together</em>. It makes no empirical claim about human leadership, tribalism, cognition, or water phases.</p>
<p><a href="data/transient_memory_protocol.json">Frozen addendum design and every condition</a> · <a href="data/transient_memory.json">Per-run measurements, intervals, and checks</a> · <a href="transient_memory.py">Runnable source</a>. The addendum is exploratory and separate from the frozen original six-group experiment.</p>'''
